apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod1
  labels:
    app: pod1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod1
  template:
    metadata:
      labels:
        app: pod1
    spec:
      containers:
      - name: pod1
        image: docker.io/anyery20k/parcialpod1:v1
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 2000
       

---

apiVersion: v1
kind: Service
metadata:
  name: pod1
spec:
  ports:
  - port: 2000
    targetPort: 2000
  selector:
    app: pod1
  type: LoadBalancer